#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=08:00:00
#PBS -l mem=8gb
#PBS -N spectral_rrtm

ulimit -s unlimited

WKDR=/scratch/mj93/run/
CCOMB=/home/mj93/models/code/spectral_rrtm/bin/mppnccombine.nyu

cd $WKDR

mpiexec -n $PBS_NP ./fms.x > stdout

# combine netcdf files
for ncfile in $(/bin/ls *.nc.0000)
do
   filename=$(basename $ncfile)
   filename=${filename%.*}
   rm $filename
   $CCOMB -r $filename ${filename}.????
   ncpdq -O $filename $filename
done

#mj
cd RESTART
for ncfile in $(/bin/ls *.nc.0000)
do
   filename=$(basename "$ncfile")
   filename="${filename%.*}"
   rm $filename
   $CCOMB -r $filename ${filename}.????
done
cd ../
#jm    

